export const movies =
        [{
                movie_id: 1,
                movie_title: 'SPIDER-MAN NO WAY HOME',
                movie_cover: 'https://www.smcinema.com/CDN/media/entity/get/FilmBackdrop/h-HO00000119?width=1024&referenceScheme=HeadOffice&allowPlaceHolder=true&fallbackMediaType=FilmTitleGraphic.jpg',
                movie_description: "Peter Parker's secret identity is revealed to the entire world. Desperate for help, Peter turns to Doctor Strange to make the world forget that he is Spider-Man. The spell goes horribly wrong and shatters the multiverse, bringing in monstrous villains that could destroy the world.",
                movie_poster: "https://terrigen-cdn-dev.marvel.com/content/prod/1x/snh_online_6072x9000_posed_01.jpg",
                movie_duration: "148",
                movie_genre: "Action, Adventure & Fantasy",
                name1: "Sam Worthington",
                name1: "Tobey Maguire",
                image1: "https://m.media-amazon.com/images/M/MV5BMTYwMTI5NTM2OF5BMl5BanBnXkFtZTcwODk3MDQ2Mg@@._V1_UY317_CR4,0,214,317_AL_.jpg",
                name2: "Tom Holland",
                image2: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Tom_Holland_by_Gage_Skidmore.jpg/220px-Tom_Holland_by_Gage_Skidmore.jpg",
                name3: "Andrew Garfield",
                image3: "https://m.media-amazon.com/images/M/MV5BMjE2MjI2OTk1OV5BMl5BanBnXkFtZTgwNTY1NzM4MDI@._V1_UY317_CR0,0,214,317_AL_.jpg",
        },
        {
                movie_id: 2,
                movie_title: "THOR LOVE AND THUNDER",
                movie_description: "Thor embarks on a journey unlike anything he's ever faced -- a quest for inner peace. However, his retirement gets interrupted by Gorr the God Butcher, a galactic killer who seeks the extinction of the gods. To combat the threat, Thor enlists the help of King Valkyrie, Korg and ex-girlfriend Jane Foster, who -- to his surprise -- inexplicably wields his magical hammer. Together, they set out on a harrowing cosmic adventure to uncover the mystery of the God Butcher's vengeance.",
                movie_cover: 'https://www.thecosmiccircus.com/wp-content/uploads/2022/07/untitled_design_645440805630157148111.png',
                movie_poster: "https://lumiere-a.akamaihd.net/v1/images/p_thorloveandthunder_639_593cb642.jpeg",
                movie_duration: "118",
                movie_genre: "Action-Adventure, Comedy, Fantasy, Romance & Superhero",
                movie_description: "Thor enlists the help of Valkyrie, Korg and ex-girlfriend Jane Foster to fight Gorr the God Butcher, who intends to make the gods extinct.",
                name1: "Chris Hemsworth",
                image1: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Chris_Hemsworth_by_Gage_Skidmore_2_%28cropped%29.jpg/220px-Chris_Hemsworth_by_Gage_Skidmore_2_%28cropped%29.jpg",
                name2: "Tessa Thompson",
                image2: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/Tessa_Thompson_by_Gage_Skidmore_3.jpg/220px-Tessa_Thompson_by_Gage_Skidmore_3.jpg",
                name3: "Natalie Portman",
                image3: "https://m.media-amazon.com/images/M/MV5BYzU0ZGRhZWItMGJlNy00YzlkLWIzOWYtNDA2NzlhMDg3YjMwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UX214_CR0,0,214,317_AL_.jpg",
        },
        {
                movie_idid: 3,
                movie_title: 'AVATAR: THE WAY OF WATER',
                movie_cover: 'https://s29288.pcdn.co/wp-content/uploads/2019/05/avatar-poster.jpg',
                movie_description: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home. When his brother is killed in a robbery, paraplegic Marine Jake Sully decides to take his place in a mission on the distant world of Pandora.",
                movie_poster: "https://m.media-amazon.com/images/M/MV5BMWFmYmRiYzMtMTQ4YS00NjA5LTliYTgtMmM3OTc4OGY3MTFkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_.jpg",
                movie_genre: "Action, Aventure & Fantasy",
                movie_duration: "105",
                movie_description: "Jake Sully lives with his newfound family formed on the planet of Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their planet.",
                name1: "Sam Worthington",
                image1: "https://m.media-amazon.com/images/M/MV5BZWUwNmEwZTUtYzMxMS00ODg5LTlmYjItMGU4ZjNmN2Q1NjkwXkEyXkFqcGdeQXVyMTM1MjAxMDc3._V1_UY317_CR5,0,214,317_AL_.jpg",
                name2: "Zoe Saldana",
                image2: "https://m.media-amazon.com/images/M/MV5BMTM2MjIwOTc0Nl5BMl5BanBnXkFtZTcwNzQ5ODM1Mw@@._V1_UX214_CR0,0,214,317_AL_.jpg",
                name3: "Jemaine Clement",
                image3: "https://m.media-amazon.com/images/M/MV5BMjE4ODY4Njc5N15BMl5BanBnXkFtZTcwMjk1ODIyMw@@._V1_UY317_CR1,0,214,317_AL_.jpg",
        }]



